"""
Django settings for simulator project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "simulator-dev-only-change-me")
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    "*",
]

SIMULATOR_FTP = {
    "HOST": os.environ.get("SIMULATOR_FTP_HOST", "ftp.iktara.ai"),
    "USERNAME": os.environ.get("SIMULATOR_FTP_USERNAME", ""),
    "PASSWORD": os.environ.get("SIMULATOR_FTP_PASSWORD", ""),
    "REMOTE_DIR": os.environ.get("SIMULATOR_FTP_REMOTE_DIR", "/Agentic NOC/Data/Aviat"),
    "ARCHIVE_DIR": os.environ.get("SIMULATOR_FTP_ARCHIVE_DIR", "/Agentic NOC/Data/Aviat/sent"),
}

SIMULATOR_FTP_BY_VENDOR = {
    "aviat": {
        **SIMULATOR_FTP,
        "REMOTE_DIR": os.environ.get("SIMULATOR_FTP_REMOTE_DIR_AVIAT", SIMULATOR_FTP["REMOTE_DIR"]),
        "ARCHIVE_DIR": os.environ.get("SIMULATOR_FTP_ARCHIVE_DIR_AVIAT", SIMULATOR_FTP["ARCHIVE_DIR"]),
    },
    "cambium": {
        **SIMULATOR_FTP,
        "REMOTE_DIR": os.environ.get("SIMULATOR_FTP_REMOTE_DIR_CAMBIUM", "/Agentic NOC/Data/CAMBIUM"),
        "ARCHIVE_DIR": os.environ.get("SIMULATOR_FTP_ARCHIVE_DIR_CAMBIUM", "/Agentic NOC/Data/CAMBIUM/sent"),
    },
}

SIMULATOR_ACCEPTANCE_SITE_ID = os.environ.get("SIMULATOR_ACCEPTANCE_SITE_ID", "UEMWBSNA01")

SIMULATOR_NIFI_HOST = os.environ.get("SIMULATOR_NIFI_HOST", "180.75.0.10")
SIMULATOR_NIFI_PORT = int(os.environ.get("SIMULATOR_NIFI_PORT", "9080"))
SIMULATOR_NIFI_PATH = os.environ.get("SIMULATOR_NIFI_PATH", "aviat")
SIMULATOR_MAX_RATE_EPS = float(os.environ.get("SIMULATOR_MAX_RATE_EPS", "100"))
SIMULATOR_INTERNAL_TOKEN = os.environ.get("SIMULATOR_INTERNAL_TOKEN", "")
SIMULATOR_AGENTICNOC_BASE_URL = os.environ.get("SIMULATOR_AGENTICNOC_BASE_URL", "")
SIMULATOR_AGENTICNOC_INTERNAL_TOKEN = os.environ.get("SIMULATOR_AGENTICNOC_INTERNAL_TOKEN", "")
SIMULATOR_AGENTICNOC_RUNTIME_URL = os.environ.get(
    "SIMULATOR_AGENTICNOC_RUNTIME_URL", "http://180.75.0.7:8000/api/stream/runtime/"
)

_db_path = Path(os.environ.get("SIMULATOR_DB_PATH", str(BASE_DIR / "data" / "db.sqlite3")))
_db_path.parent.mkdir(parents=True, exist_ok=True)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simulator_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simulator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simulator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "simulator_app" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

REDIS_HOST = os.environ.get("SIMULATOR_REDIS_HOST", "180.75.0.15")
REDIS_PORT = int(os.environ.get("SIMULATOR_REDIS_PORT", "6379"))
REDIS_DB = int(os.environ.get("SIMULATOR_REDIS_DB", "0"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
