"""
Django settings for simulator project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path


def _load_env_file(filepath: Path) -> None:
    """Load environment variables from a .env file into os.environ if not already set."""
    if not filepath.is_file():
        return
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, _, val = line.partition("=")
                key = key.strip()
                val = val.strip()
                if (val.startswith('"') and val.endswith('"')) or (
                    val.startswith("'") and val.endswith("'")
                ):
                    val = val[1:-1]
                os.environ.setdefault(key, val)


BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv

    _env_file = os.environ.get("ENV_FILE")
    if _env_file:
        load_dotenv(_env_file)
    else:
        load_dotenv(BASE_DIR / ".env")
        if Path(".env").resolve() != (BASE_DIR / ".env").resolve():
            load_dotenv(Path(".env"))
except ImportError:
    _env_file = os.environ.get("ENV_FILE")
    if _env_file:
        _load_env_file(Path(_env_file))
    else:
        _load_env_file(BASE_DIR / ".env")
        if Path(".env").resolve() != (BASE_DIR / ".env").resolve():
            _load_env_file(Path(".env"))

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "simulator-dev-only-change-me")
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    "*",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:9019",
    "http://127.0.0.1:9019",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://*.iktara.ai:9019",
    "https://*.iktara.ai:9019",
    "http://*.iktara.ai",
    "https://*.iktara.ai",
    "http://*.iktaratech.com:9019",
    "https://*.iktaratech.com:9019",
    "http://*.iktaratech.com",
    "https://*.iktaratech.com",
    "http://216.48.189.217:9019",
    "http://216.48.189.217:8000",
    "http://216.48.189.217",
]
_env_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if _env_csrf:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in _env_csrf.split(",") if origin.strip()])

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_AGE = 604800  # 7 days


SIMULATOR_FTP = {
    "HOST": os.environ.get("SIMULATOR_FTP_HOST", "ftp.iktara.ai"),
    "USERNAME": os.environ.get("SIMULATOR_FTP_USERNAME", ""),
    "PASSWORD": os.environ.get("SIMULATOR_FTP_PASSWORD", ""),
    "REMOTE_DIR": os.environ.get("SIMULATOR_FTP_REMOTE_DIR", "/Agentic NOC/Data/Aviat"),
    "ARCHIVE_DIR": os.environ.get("SIMULATOR_FTP_ARCHIVE_DIR", "/Agentic NOC/Data/Aviat/sent"),
}

SIMULATOR_FTP_BY_VENDOR = {
    "aviat": {
        **SIMULATOR_FTP,
        "REMOTE_DIR": os.environ.get("SIMULATOR_FTP_REMOTE_DIR_AVIAT", SIMULATOR_FTP["REMOTE_DIR"]),
        "ARCHIVE_DIR": os.environ.get("SIMULATOR_FTP_ARCHIVE_DIR_AVIAT", SIMULATOR_FTP["ARCHIVE_DIR"]),
    },
    "cambium": {
        **SIMULATOR_FTP,
        "REMOTE_DIR": os.environ.get("SIMULATOR_FTP_REMOTE_DIR_CAMBIUM", "/Agentic NOC/Data/CAMBIUM"),
        "ARCHIVE_DIR": os.environ.get("SIMULATOR_FTP_ARCHIVE_DIR_CAMBIUM", "/Agentic NOC/Data/CAMBIUM/sent"),
    },
}

SIMULATOR_ACCEPTANCE_SITE_ID = os.environ.get("SIMULATOR_ACCEPTANCE_SITE_ID", "UEMWBSNA01")

SIMULATOR_NIFI_HOST = os.environ.get("SIMULATOR_NIFI_HOST", "180.75.0.10")
SIMULATOR_NIFI_PORT = int(os.environ.get("SIMULATOR_NIFI_PORT", "9080"))
SIMULATOR_NIFI_PATH = os.environ.get("SIMULATOR_NIFI_PATH", "aviat")
SIMULATOR_MAX_RATE_EPS = float(os.environ.get("SIMULATOR_MAX_RATE_EPS", "100"))
SIMULATOR_INTERNAL_TOKEN = os.environ.get("SIMULATOR_INTERNAL_TOKEN", "")
# The AgenticNOC service URL and credential are deployment inputs.  Never use
# a guessed host or a committed token: an unset value must make the proxy
# unavailable rather than silently downgrade authentication.
SIMULATOR_AGENTICNOC_BASE_URL = os.environ.get("SIMULATOR_AGENTICNOC_BASE_URL", "").rstrip("/")
SIMULATOR_AGENTICNOC_PUBLIC_URL = os.environ.get("SIMULATOR_AGENTICNOC_PUBLIC_URL", "").rstrip("/")
SIMULATOR_AGENTICNOC_INTERNAL_TOKEN = os.environ.get("SIMULATOR_AGENTICNOC_INTERNAL_TOKEN", "")
SIMULATOR_AGENTICNOC_RUNTIME_URL = os.environ.get(
    "SIMULATOR_AGENTICNOC_RUNTIME_URL", ""
)

_db_path = Path(os.environ.get("SIMULATOR_DB_PATH", str(BASE_DIR / "data" / "db.sqlite3")))
_db_path.parent.mkdir(parents=True, exist_ok=True)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'simulator_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'simulator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'simulator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "simulator_app" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

REDIS_HOST = os.environ.get("SIMULATOR_REDIS_HOST", "180.75.0.15")
REDIS_PORT = int(os.environ.get("SIMULATOR_REDIS_PORT", "6379"))
REDIS_DB = int(os.environ.get("SIMULATOR_REDIS_DB", "0"))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
